#!/usr/bin/env bash

set -eo pipefail

if [[ -x "$(command -v brew)" ]];then
  exit 0
fi

xcode-select --install
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
