#!/usr/bin/env zsh

if [[ -x "$(command -v git)" ]]; then
  tags=$(git tag)
  local selected_tag=$(echo ${tags} | fzf)
  if [[ -n $selected_tag ]]; then
    git checkout $selected_tag
  fi
else
  echo "Please Install git!!!"
fi
