add_newline = false
format = """
[┌─](bold fg:#a89984) $username$directory$git_branch$git_commit$git_status$terraform
[└─](bold fg:#a89984) """

[username]
show_always = true
format = "[$user](fg:#8ec07c) in "

[directory]
style = "fg:#fabd2f"

[git_branch]
only_attached = true
style = "#fe8019"

[git_commit]
tag_disabled = false
style = "#fe8019"
format = "on [ $hash$tag]($style) "

[git_status]
style = "#fe8019"
