#!/usr/bin/env bash

set -e -o pipefail

readonly DENY_BRANCH_REGEX='^(master|main|release.*|gh-pages)$'

## check secrets
git secrets --pre_commit_hook -- "$@"

## check protected branches
git_allow_file=".git/git_allow"
[[ -f ${git_allow_file} ]] && exit 0

branch=$(git branch --no-color --show-current)
if [[ ${branch} =~ ${DENY_BRANCH_REGEX} ]]; then
  echo "ERROR: Failed to commit to ${branch} branch"
  echo "       ${branch} branch is protected."
  exit 1
fi
