#!/usr/bin/env bash

sudo chmod 700 ${HOME}
sudo chown ${USER}:${USER} ${HOME}

# setup dotfiles
dotfiles_path=${HOME}/src/github.com/uesyn/dotfiles
if [[ ! -d "${dotfiles_path}" ]]; then
  git clone https://github.com/uesyn/dotfiles ${dotfiles_path}
fi
cd ${dotfiles_path}
./bootstrap

tail -f /dev/null
