#!/bin/sh

# Dind wrapper script from docker team, adapted to a function
# Maintained: https://github.com/moby/moby/blob/master/hack/dind 
if [ -d /sys/kernel/security ] && ! mountpoint -q /sys/kernel/security; then
	sudo mount -t securityfs none /sys/kernel/security || {
		echo >&2 'Could not mount /sys/kernel/security.'
		echo >&2 'AppArmor detection and --privileged mode might break.'
	}
fi

## Mount /tmp (conditionally)
if ! mountpoint -q /tmp; then
	sudo mount -t tmpfs none /tmp
fi

## cgroup v2: enable nesting
if [ -f /sys/fs/cgroup/cgroup.controllers ]; then
	# move the processes from the root group to the /init group,
	# otherwise writing subtree_control fails with EBUSY.
	# An error during moving non-existent process (i.e., "cat") is ignored.
	sudo mkdir -p /sys/fs/cgroup/init
	sudo bash -c "xargs -rn1 < /sys/fs/cgroup/cgroup.procs > /sys/fs/cgroup/init/cgroup.procs || :"
	# enable controllers
	sudo bash -c "sed -e 's/ / +/g' -e 's/^/+/' < /sys/fs/cgroup/cgroup.controllers > /sys/fs/cgroup/cgroup.subtree_control"
fi

exec dockerd --registry-mirror https://mirror.gcr.io --mtu=${DOCKER_MTU:-1280} --bip=172.23.0.254/24
