default:
  podSpec:
    containers:
    - image: ghcr.io/uesyn/devbox:latest
      name: devbox
      securityContext:
        privileged: true
      volumeMounts:
      - name: tmp
        mountPath: /tmp
      - name: docker
        mountPath: /var/lib/docker
      - name: data
        mountPath: /home/devbox
    volumes:
    - name: tmp
      emptyDir: {}
    - name: docker
      emptyDir: {}
    - name: data
      persistentVolumeClaim:
        claimName: data
  persistentVolumeClaims:
    data:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
  exec:
    shell: zsh
    envs:
      PROMPT_ICON: 
    hostEnvs:
    - GITHUB_TOKEN
    - GH_ENTERPRISE_TOKEN
