exec:
  default:
    command:
    - zsh
    env:
      PROMPT_ICON:
        Value: "🍎"
      GITHUB_TOKEN:
        Value: "${GITHUB_TOKEN}"
      GITLAB_TOKEN:
        Value: "${GITLAB_TOKEN}"
      GITLAB_ENTERPRISE_HOST:
        Value: "${GITLAB_ENTERPRISE_HOST}"
      GITLAB_ENTERPRISE_TOKEN:
        Value: "${GITLAB_ENTERPRISE_TOKEN}"
      GH_ENTERPRISE_TOKEN:
        Value: "${GH_ENTERPRISE_TOKEN}"