template:
  loadRestrictionsNone: true
ssh:
  shell: zsh
exec:
  command:
  - gosu
  - devbox
  - zsh
envs:
- name: PROMPT_ICON
  raw: "🍎"
- name: GITHUB_TOKEN
  hostEnv: GITHUB_TOKEN
- name: GITLAB_TOKEN
  hostEnv: GITLAB_TOKEN
- name: GITLAB_ENTERPRISE_HOST
  hostEnv: GITLAB_ENTERPRISE_HOST
- name: GITLAB_ENTERPRISE_TOKEN
  hostEnv: GITLAB_ENTERPRISE_TOKEN
- name: GH_ENTERPRISE_TOKEN
  hostEnv: GH_ENTERPRISE_TOKEN