exec:
  shell: zsh
  envs:
    PROMPT_ICON: "🍎"
    GITHUB_TOKEN: "${GITHUB_TOKEN}"
    GITLAB_TOKEN: "${GITLAB_TOKEN}"
    GH_ENTERPRISE_TOKEN: "${GH_ENTERPRISE_TOKEN}"
devbox:
  image: ghcr.io/uesyn/devbox
  startupProbeCommand:
  - test
  - -d
  - /home/devbox/.local/share/aquaproj-aqua
  privileged: true
  requests:
    cpu: 1000m
    memory: 2Gi
    ephemeral-storage: 5Gi
  volumes:
  - name: home
    mountPath: /home/devbox
    persistentVolumeClaim:
      size: 30Gi
  - name: docker
    mountPath: /var/lib/docker
    persistentVolumeClaim:
      size: 30Gi
  - name: tls
    mountPath: /etc/ssl/certs
    hostPath:
      path: /etc/ssl/certs