apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devbox-home
spec:
  accessModes: 
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: devbox
  name: devbox
spec:
  dnsPolicy: Default
  shareProcessNamespace: true
  terminationGracePeriodSeconds: 3600
  containers:
  - image: ghcr.io/uesyn/devbox:latest
    name: devbox
    lifecycle:
      preStop:
        exec:
          command:
          - /bin/bash
          - -c
          - |
            # Stop devbox when zellij, tmux and nvim are inactive or timeout is reached.
            touch /tmp/stopping
            end="\$(( \$(date +%s) + 1800 ))"

            while [[ "\$(date +%s)" -lt "\${end}" ]]; do
              [[ "\$(ps -lC zellij | wc -l)" -eq 1 ]] && break
              sleep 1s
            done

            while [[ "\$(date +%s)" -lt "\${end}" ]]; do
              [[ "\$(ps -lC tmux | wc -l)" -eq 1 ]] && break
              sleep 1s
            done

            while [[ "\$(date +%s)" -lt "\${end}" ]]; do
              [[ "\$(ps -lC nvim | wc -l)" -eq 1 ]] && break
              sleep 1s
            done

            rm /tmp/stopping
            sudo pkill supervisord
    securityContext:
      privileged: true
    volumeMounts:
    - name: docker
      mountPath: /var/lib/docker
    - name: data
      mountPath: /home/devbox
  volumes:
  - name: docker
    emptyDir: {}
  - name: data
    persistentVolumeClaim:
      claimName: devbox-home
