exec:
  shell: zsh
  envs:
    PROMPT_ICON: "🍎"
    GITHUB_TOKEN: "${GITHUB_TOKEN}"
    GH_ENTERPRISE_TOKEN: "${GH_ENTERPRISE_TOKEN}"
devbox:
  image: ghcr.io/uesyn/devbox
  privileged: true
  hostPID: false
  terminationGracePeriodSeconds: 3600
  requests:
    cpu: 500m
    memory: 1Gi
    ephemeral-storage: 5Gi
  volumes:
  - name: home
    mountPath: /home/devbox
    persistentVolumeClaim:
      size: 50Gi
  - name: docker
    mountPath: /var/lib/docker
    emptyDir: {}
  - name: tls
    mountPath: /etc/ssl/certs
    hostPath:
      path: /etc/ssl/certs