" Generated by vim-plug
" Wed 02 Jun 2021 11:11:15 AM JST
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['coc-go'].commit = '731661a76dd71df7ef9b362ee180e3b35d81e318'
silent! let g:plugs['coc-json'].commit = '6bb083dbbd24b4bc5213d4de125e8c23a37e7422'
silent! let g:plugs['coc-tabnine'].commit = '027cff08bc8fdb53b56757a51bdf22f6de1b5b3f'
silent! let g:plugs['coc-tsserver'].commit = 'cd624aa05e2cfd0f6a31473f44e95ee450ef2886'
silent! let g:plugs['coc-yaml'].commit = '2acb0ae832531ee12aedfa695c074d017b5cac4d'
silent! let g:plugs['coc.nvim'].commit = '1a74bf3c57fec8442f837b3baad0d6fb75d1b97a'
silent! let g:plugs['fern-git-status.vim'].commit = '5c9fc219d9b8cd3e39e78d285874665f79ffb1b4'
silent! let g:plugs['fern-renderer-nerdfont.vim'].commit = '942be10bda577ba4840c4a939200f05024b8603c'
silent! let g:plugs['fern.vim'].commit = '5fe781e4a12101871bc778b977ce6b76685c1ab0'
silent! let g:plugs['fzf'].commit = 'e086f0b3fe1cb56df1335037cfd3d612defce082'
silent! let g:plugs['fzf.vim'].commit = 'e34f6c129d39b90db44df1107c8b7dfacfd18946'
silent! let g:plugs['glyph-palette.vim'].commit = '9da4d62ec2d9057b923581e906a4231de3150df9'
silent! let g:plugs['gruvbox'].commit = 'bf2885a95efdad7bd5e4794dd0213917770d79b7'
silent! let g:plugs['gv.vim'].commit = '5f902f4f7d06ef084ffd6cddcd1ee7d3c9a793c6'
silent! let g:plugs['incsearch.vim'].commit = '25e2547fb0566460f5999024f7a0de7b3775201f'
silent! let g:plugs['nerdfont.vim'].commit = 'ebc32d87a086b66d86e7cc52b73c1de8f413678a'
silent! let g:plugs['vim-fugitive'].commit = '10ed70a9c23cdd1748444e89e4928282e510451d'
silent! let g:plugs['vim-gitgutter'].commit = '10998f303cd85405e51380f6dc406dd756c105e8'
silent! let g:plugs['vim-markdown'].commit = '8e5d86f7b85234d3d1b4207dceebc43a768ed5d4'
silent! let g:plugs['vim-terraform'].commit = '9166d42e5dc9bc0ef7e1b9e93d52bb4c5b923560'
silent! let g:plugs['vista.vim'].commit = '19cad968d2cd759e7f9de1d662ec680bd93ebebc'
silent! let g:plugs['winresizer'].commit = '9dc9899cedf84d78b93263b1fdb105b37c54c7b5'

PlugUpdate!

