" Generated by vim-plug
" Thu May 27 20:03:52 2021
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['coc-go'].commit = '4ee552edc0449f4d99741f53d7b385500e1da21e'
silent! let g:plugs['coc-json'].commit = '6bb083dbbd24b4bc5213d4de125e8c23a37e7422'
silent! let g:plugs['coc-tabnine'].commit = '027cff08bc8fdb53b56757a51bdf22f6de1b5b3f'
silent! let g:plugs['coc-tsserver'].commit = 'ed3886f4c8c767e78f25d95117c26f22e84724b6'
silent! let g:plugs['coc-yaml'].commit = '2acb0ae832531ee12aedfa695c074d017b5cac4d'
silent! let g:plugs['coc.nvim'].commit = '1a74bf3c57fec8442f837b3baad0d6fb75d1b97a'
silent! let g:plugs['fern-git-status.vim'].commit = '5c9fc219d9b8cd3e39e78d285874665f79ffb1b4'
silent! let g:plugs['fern-renderer-nerdfont.vim'].commit = '942be10bda577ba4840c4a939200f05024b8603c'
silent! let g:plugs['fern.vim'].commit = '5fe781e4a12101871bc778b977ce6b76685c1ab0'
silent! let g:plugs['fzf'].commit = 'a4bc08f5a35da6e374a2ce0da4c931d7fd32fdf1'
silent! let g:plugs['fzf.vim'].commit = 'e34f6c129d39b90db44df1107c8b7dfacfd18946'
silent! let g:plugs['glyph-palette.vim'].commit = '9da4d62ec2d9057b923581e906a4231de3150df9'
silent! let g:plugs['gruvbox'].commit = 'bf2885a95efdad7bd5e4794dd0213917770d79b7'
silent! let g:plugs['gv.vim'].commit = '5f902f4f7d06ef084ffd6cddcd1ee7d3c9a793c6'
silent! let g:plugs['incsearch.vim'].commit = '25e2547fb0566460f5999024f7a0de7b3775201f'
silent! let g:plugs['nerdfont.vim'].commit = 'ebc32d87a086b66d86e7cc52b73c1de8f413678a'
silent! let g:plugs['open-browser-github.vim'].commit = 'ac7c034e300f36d591ef234dcd5eb5cd5c07c74f'
silent! let g:plugs['open-browser.vim'].commit = 'd6f1784685abdd86500fdb5fa2fbaf2aab833f18'
silent! let g:plugs['suda.vim'].commit = 'fbb138f5090c3db4dabeba15326397a09df6b73b'
silent! let g:plugs['vim-fugitive'].commit = '28afd121511db9c4c4d070a0dc3ebb2ed5360328'
silent! let g:plugs['vim-gitgutter'].commit = '10998f303cd85405e51380f6dc406dd756c105e8'
silent! let g:plugs['vim-markdown'].commit = '8e5d86f7b85234d3d1b4207dceebc43a768ed5d4'
silent! let g:plugs['vim-yaml'].commit = 'dce19542d5ec1663183b0f6844ec663b5d1f3d24'
silent! let g:plugs['vista.vim'].commit = '3d4e2a80658467af02a6347e3dae8810e6a5f02f'
silent! let g:plugs['winresizer'].commit = 'f64e556586f3e35f14c009f110443231442c9ae7'

PlugUpdate!

