#!/usr/bin/env zsh

if [[ -x "$(command -v ghq)" ]]; then
  list=($(ghq list) tmp)
  local selected_dir=$(for e in "${list[@]}"; do echo "$e"; done | sort | uniq | fzf)
  if [[ -n $selected_dir ]]; then
    if [[ $selected_dir == "tmp" ]]; then
      mkdir -p $(ghq root)/${selected_dir}
    fi
    cd $(ghq root)/${selected_dir}
  fi
else
  echo "Please Install ghq!!!"
fi
