ssh:
  command:
  - zsh
exec:
  command:
  - gosu
  - devbox
  - zsh
envs:
- name: PROMPT_ICON
  raw: "🍎"
- name: GITHUB_TOKEN
  hostEnv: GITHUB_TOKEN
- name: GITLAB_TOKEN
  hostEnv: GITLAB_TOKEN
- name: GITLAB_ENTERPRISE_HOST
  hostEnv: GITLAB_ENTERPRISE_HOST
- name: GITLAB_ENTERPRISE_TOKEN
  hostEnv: GITLAB_ENTERPRISE_TOKEN
- name: GH_ENTERPRISE_TOKEN
  hostEnv: GH_ENTERPRISE_TOKEN
- name: OPENAI_API_KEY
  hostEnv: OPENAI_API_KEY
podSpec:
  automountServiceAccountToken: false
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
  containers:
  - name: devbox
    image: ghcr.io/uesyn/devcontainer
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
    stdin: true
    tty: true
    workingDir: /home/devbox
    lifecycle:
      postStart:
        exec:
          command:
          - gosu
          - devbox
          - /bin/bash
          - -c
          - |
            export HOME=/home/devbox
            DOTFILES_DIR=${HOME}/src/github.com/uesyn/dotfiles
            if [[ ! -d ${DOTFILES_DIR} ]]; then
              git clone https://github.com/uesyn/dotfiles ${DOTFILES_DIR}
              bash ${DOTFILES_DIR}/bootstrap
            fi
            SSH_DIR=${HOME}/.ssh
            AUTHORIZED_KEYS=${SSH_DIR}/authorized_keys
            mkdir -p ${SSH_DIR}
            cat << 'EOF' > ${AUTHORIZED_KEYS}
            ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILyZa1D5S8H02Z6HJA3Sk6Ira//HFo7RLLbuHRbUA6Po
            ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBA+eqVhJIrUCJFzJuGMiv8UNrUtsktuPD/lVizoZkUTgjQPG0XWfr+WromEt7mDY1rO6jACKSEMNsiBfQa+ucF0=
            EOF
            chmod 700 ${SSH_DIR}; chmod 600 ${AUTHORIZED_KEYS}; chown -R devbox ${SSH_DIR}
    volumeMounts:
    - name: data
      mountPath: /home/devbox
      subPath: home
    - name: data
      mountPath: /var/lib/docker
      subPath: var-lib-docker
    - name: docker-config
      mountPath: /etc/docker
    - name: tls-certs
      mountPath: /etc/ssl/certs
      readOnly: true
    securityContext:
      privileged: true
    ports:
    - name: ssh
      containerPort: 22
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data
  - name: docker-config
    configMap:
      name: docker-config
  - name: tls-certs
    hostPath:
      path: /etc/ssl/certs
  dnsPolicy: Default
  dnsConfig:
    options:
    - name: single-request-reopen
  terminationGracePeriodSeconds: 1
pvcs:
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
cms:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: docker-config
  data:
    daemon.json: |
      {
        "bip": "172.31.100.1/24",
        "mtu": 1450,
        "dns-search": ["."]
      }