apiVersion: v1
kind: Pod
metadata:
  name: devbox
spec:
  volumes:
  - name: home
    persistentVolumeClaim:
      $patch: delete
    emptyDir: {}
  - name: var-lib-docker
    persistentVolumeClaim:
      $patch: delete
    emptyDir: {}