apiVersion: v1
kind: Pod
metadata:
  name: devbox
spec:
  automountServiceAccountToken: false
  securityContext:
    fsGroup: 1000
  containers:
  - name: devbox
    image: ghcr.io/uesyn/devbox
    stdin: true
    tty: true
    lifecycle:
      postStart:
        exec:
          command:
          - gosu
          - devbox
          - /bin/bash
          - -c
          - |
            export HOME=/home/devbox
            DOTFILES_DIR=${HOME}/src/github.com/uesyn/dotfiles
            if [[ -d ${DOTFILES_DIR} ]]; then
              exit
            fi
            git clone https://github.com/uesyn/dotfiles ${DOTFILES_DIR}
            bash ${DOTFILES_DIR}/bootstrap
    volumeMounts:
    - name: home
      mountPath: /home/devbox
    - name: var-lib-docker
      mountPath: /var/lib/docker
    - name: docker-config
      mountPath: /etc/docker
    securityContext:
      privileged: true
  volumes:
  - name: home
    persistentVolumeClaim:
      claimName: home
  - name: var-lib-docker
    persistentVolumeClaim:
      claimName: var-lib-docker
  - name: docker-config
    configMap:
      name: docker-config
  terminationGracePeriodSeconds: 1
