apiVersion: v1
kind: Pod
metadata:
  name: devbox
spec:
  automountServiceAccountToken: false
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
  containers:
  - name: devbox
    image: ghcr.io/uesyn/devbox
    stdin: true
    tty: true
    workingDir: /home/devbox
    lifecycle:
      postStart:
        exec:
          command:
          - gosu
          - devbox
          - /bin/bash
          - -c
          - |
            export HOME=/home/devbox
            DOTFILES_DIR=${HOME}/src/github.com/uesyn/dotfiles
            if [[ -d ${DOTFILES_DIR} ]]; then
              exit
            fi
            git clone https://github.com/uesyn/dotfiles ${DOTFILES_DIR}
            bash ${DOTFILES_DIR}/bootstrap
            export SSH_DIR=${HOME}/.ssh
            export AUTHORIZED_KEYS=${SSH_DIR}/authorized_keys
            mkdir -p ${SSH_DIR}
            echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILyZa1D5S8H02Z6HJA3Sk6Ira//HFo7RLLbuHRbUA6Po' > ${AUTHORIZED_KEYS}
            chmod 700 ${SSH_DIR}; chmod 600 ${AUTHORIZED_KEYS}; chown -R devbox ${SSH_DIR}
    volumeMounts:
    - name: data
      mountPath: /home/devbox
      subPath: home
    - name: data
      mountPath: /var/lib/docker
      subPath: var-lib-docker
    - name: docker-config
      mountPath: /etc/docker
    securityContext:
      privileged: true
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data
  - name: docker-config
    configMap:
      name: docker-config
  dnsPolicy: Default
  dnsConfig:
    options:
    - name: single-request-reopen
  terminationGracePeriodSeconds: 1
