apiVersion: v1
kind: Pod
metadata:
  name: devbox
spec:
  automountServiceAccountToken: false
  securityContext:
    fsGroup: 1000
  containers:
  - name: devbox
    image: ghcr.io/uesyn/devbox
    stdin: true
    tty: true
    workingDir: /home/devbox
    lifecycle:
      postStart:
        exec:
          command:
          - gosu
          - devbox
          - /bin/bash
          - -c
          - |
            export HOME=/home/devbox
            DOTFILES_DIR=${HOME}/src/github.com/uesyn/dotfiles
            if [[ -d ${DOTFILES_DIR} ]]; then
              exit
            fi
            git clone https://github.com/uesyn/dotfiles ${DOTFILES_DIR}
            bash ${DOTFILES_DIR}/bootstrap
    volumeMounts:
    - name: data
      mountPath: /home/devbox
      subPath: home
    - name: data
      mountPath: /var/lib/docker
      subPath: var-lib-docker
    - name: docker-config
      mountPath: /etc/docker
    securityContext:
      privileged: true
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data
  - name: docker-config
    configMap:
      name: docker-config
  terminationGracePeriodSeconds: 1
