apiVersion: v1
kind: Pod
metadata:
  name: devbox
spec:
  containers:
  - name: devbox
    image: ghcr.io/uesyn/devbox
    env:
    - name: DOCKER_HOST
      value: tcp://localhost:2375
    lifecycle:
      postStart:
        exec:
          command:
          - /bin/sh
          - -c
          - |-
            DOTFILES_DIR="/root/src/github.com/uesyn/dotfiles"
            if [[ -d ${DOTFILES_DIR} ]]; then
              exit
            fi
            git clone https://github.com/uesyn/dotfiles ${DOTFILES_DIR}
            ${DOTFILES_DIR}/bootstrap
    volumeMounts:
    - name: home
      mountPath: /root
  - name: docker
    image: docker:dind
    args:
    - --mtu=1280
    - --bip=172.23.0.254/24
    - --registry-mirror=https://mirror.gcr.io
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ""
    securityContext:
      privileged: true
    volumeMounts:
    - name: var-lib-docker
      mountPath: /var/lib/docker
    - name: home
      mountPath: /root
  volumes:
  - name: home
    persistentVolumeClaim:
      claimName: home
  - name: var-lib-docker
    emptyDir: {}
  terminationGracePeriodSeconds: 1
