kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: home
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: var-lib-docker
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
