apiVersion: v1
kind: Service
metadata:
  annotations:
    devbox.uesyn.net/ssh: "true"
  name: devbox-ssh
spec:
  type: NodePort
  selector:
    app: devbox
  ports:
  - name: ssh
    port: 22
    targetPort: ssh
---
apiVersion: v1
kind: Service
metadata:
  name: devbox
spec:
  clusterIP: None
  selector:
    app: devbox
