apiVersion: v1
kind: Pod
metadata:
  name: devbox
spec:
  automountServiceAccountToken: false
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
  containers:
  - name: devbox
    image: ghcr.io/uesyn/devcontainer
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
    stdin: true
    tty: true
    workingDir: /home/devbox
    lifecycle:
      postStart:
        exec:
          command:
          - gosu
          - devbox
          - /bin/bash
          - -c
          - |
            export HOME=/home/devbox
            DOTFILES_DIR=${HOME}/src/github.com/uesyn/dotfiles
            if [[ -d ${DOTFILES_DIR} ]]; then
              exit
            fi
            git clone https://github.com/uesyn/dotfiles ${DOTFILES_DIR}
            bash ${DOTFILES_DIR}/bootstrap
            export SSH_DIR=${HOME}/.ssh
            export AUTHORIZED_KEYS=${SSH_DIR}/authorized_keys
            mkdir -p ${SSH_DIR}
            echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILyZa1D5S8H02Z6HJA3Sk6Ira//HFo7RLLbuHRbUA6Po' > ${AUTHORIZED_KEYS}
            echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCiIRDaR1uJSE4dDACs9H/llfzLipQEp6vsAa+QR+9QlOE3rARiH5rmHP8JyLRywGmgmLwaf0jWq5hbprsoEuW/VsEMGGOIaISNo43/UdmUdgyiU5kKGzaaNDmjoYcCdrUYxBgc0XsUtqiLUvJvU2uor11kRn7mV8sLR+gYfDhu/E9/MVdXw8serXRb8iRIZWdOY1CW6WsYvkjEYMZoyDxhwwc5wq7BdWF9/yMbBF8P3moVOSDv9D+GDP6GUXYOCmNvTmYrP+ayxsvGYvfsu7daHiClHQS9WZcTshGjL3DOKv+VokdidIGjkFVO6d+5qVwf8bC0V/+35M7o49VzL8sKN9Y6qsQns/+9IEQZevGCLPsvb7ehs4t6KHddGx3qtpTSxlUBdjTqk5ylTC6TlE3dp+DTybxTUHeOhbX/UoE27jE1NIVl7VL+wDzUfx2FJvFpnSm5FKp0DyabLtX3uJJG68nR7aDB0URtBathI1oZXAHCGNeQA7Zml17Q1hR0QUufKCY1cAMjyDXc6ru9COIs+8n+e/13kQPJSUrYTLwOaJiP2umjeWHmwOF1ZXgpiA/vCyLxmpMK3/Y6v4eqkcgkEgEC7N6xBW5szZ5Mts7wkE6HgAopKkCmW6IVwYDtd61vKR92M9KBW2pZCyKeObB0mtfSKwn7k0QuRhkLBJme1w==' >> ${AUTHORIZED_KEYS}
            echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCtSKlrVJ1zg+YroGr1ip43fiPzk0iGbe2eArfjF60pZm+7/4p9OGVNk0gFckw8qCUoviNkLxGpx51x6cW5ox196rDG5d0j9PRI6wOqifP9SOGhqhgbV91M1slA6IMaUXSFKXUsFURgEu3WAWXoYsRJ76eaG36xp9jwecuuETDqPXWM8FwBFyt0zK9wcIfsII0Hu65H0M69dwiSodYl7F9KuumBPBeh5Gf9tbtEQCtPyX2Q7EVDSM0aRMxiF+Axi5weavn70jlg0qex7PG8DM8NIyToqjAjFd4epwoQypbpwXWHAbrD4xQOthfNSJdcrEUpOQ9YzLAiuQ+JfKFvrNznwJ+B0tTnwFZ71+gTJOAxGV623nAcnJyprKmAdCMmSwt/ippabp+wunPvSpL+qkBROpC0e/45xppXoD9DYWR6jruFzjvfLjW7NAONty5EFCxytfr/V7P7MdnjgXUVdrleMIVr25XEbQPQ1EzT+huto9KmiGBZ+NGxF3/zAu4tVG4jOuV8n1QaEDbJou+Wq55IB4OVgMsIN5FWisNuc15wZ5El10mh1P5V/hAVfVq25r4wtMZLhtia3Dlg9a5mZF8nJmnatrYv5EnfLBHJ1d8fOe5X+jeZNosgKCLNLqbFPRcFOZRM/NqCfxnzP5CLQtPI7Nxfpu+p5M1TtcbWaDHcsQ==' >> ${AUTHORIZED_KEYS}
            chmod 700 ${SSH_DIR}; chmod 600 ${AUTHORIZED_KEYS}; chown -R devbox ${SSH_DIR}
    volumeMounts:
    - name: data
      mountPath: /home/devbox
      subPath: home
    - name: data
      mountPath: /var/lib/docker
      subPath: var-lib-docker
    - name: docker-config
      mountPath: /etc/docker
    - name: tls-certs
      mountPath: /etc/ssl/certs
      readOnly: true
    securityContext:
      privileged: true
    ports:
    - name: ssh
      containerPort: 22
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data
  - name: docker-config
    configMap:
      name: docker-config
  - name: tls-certs
    hostPath:
      path: /etc/ssl/certs
  dnsPolicy: Default
  dnsConfig:
    options:
    - name: single-request-reopen
  terminationGracePeriodSeconds: 1
