kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data
  labels:
    devk.uesyn.dev/stop-policy: "retain"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
