apiVersion: v1
kind: Service
metadata:
  labels:
    devk.uesyn.dev/part-of: "ssh"
  name: devbox-ssh
spec:
  type: NodePort
  selector:
    app: devbox
  ports:
  - name: ssh
    port: 22
    targetPort: ssh
