apiVersion: v1
kind: Service
metadata:
  annotations:
    devk.uesyn.dev/ssh-user: "devbox"
  labels:
    devk.uesyn.dev/part-of: "selector"
  name: devbox
spec:
  type: NodePort
  selector:
    app: devbox
  ports:
  - name: ssh
    port: 22
    targetPort: ssh
