#!/usr/bin/env bash

set -e -o pipefail

function usage() {
  cat << EOF
git-allow let allow push or commit for restricted branches.

Usage:
	git-allow [arguments]

The arguments are:
	--yes,-y    allow git push or commit for restricted branches.
	--no,-n     deny git push or commit for restricted branches.
EOF
}

allow=
deny=
for arg in "$@"; do
  case $arg in
    --yes|-y)
      allow="y"
      ;;
    --no|-n)
      deny="y"
      ;;
  esac
done

if [[ -z $allow && -z $deny ]]; then
  usage
  exit 1
fi

root="$(git rev-parse --show-toplevel 2>/dev/null)"
branch=$(git branch --no-color --show-current)
dotgit="${root}/.git"
allow_file="${dotgit}/git_allow"

if [[ -n $deny ]]; then
  rm -f ${allow_file}
  exit 0
fi

if [[ -n $allow ]]; then
  touch ${allow_file}
  exit 0
fi
