#!/usr/bin/env bash

set -e -o pipefail

git_allow_file=".git/git_allow"
[[ -f ${git_allow_file} ]] && exit 0

readonly DENY_BRANCH_REGEX='^(master|main|release.*|gh-pages)$'

read local_ref local_sha remote_ref remote_sha
remote_branch=${remote_ref##"refs/heads/"}
if [[ "${remote_branch}" =~ ${DENY_BRANCH_REGEX} ]]; then
  echo "ERROR: Failed to push to remote ${remote_branch}."
  echo "       ${remote_branch} branch is protected."
  exit 1
fi
