if [[ -z ${OLD_PATH} ]]; then
	export OLD_PATH=${PATH}
fi
PATH=${OLD_PATH}

# nix
if [[ -f ~/.local/state/nix/profiles/profile/etc/profile.d/hm-session-vars.sh ]]; then
  source ~/.local/state/nix/profiles/profile/etc/profile.d/hm-session-vars.sh
fi
export TERMINFO_DIRS="/usr/share/terminfo:${HOME}/.nix-profile/share/terminfo"
export PATH="${HOME}/.nix-profile/bin:${PATH}"

[[ -f /usr/local/bin/brew ]] && eval $(/usr/local/bin/brew shellenv)
[[ -f /opt/homebrew/bin/brew ]] && eval $(/opt/homebrew/bin/brew shellenv)
[[ -f /home/linuxbrew/.linuxbrew/bin/brew ]] && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
export HOMEBREW_NO_AUTO_UPDATE=1

# common
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

## opt
export OPT_DIR=${OPT_DIR:-${HOME}/opt}
export OPT_BIN=${OPT_DIR}/bin
export PATH=${OPT_BIN}:${PATH}

# go
export GOPATH=${HOME}
export GOBIN=${OPT_BIN}

# krew
export PATH=${PATH}:${HOME}/.krew/bin

# raise OPT_BIN path priority
PATH=${OPT_BIN}:$PATH
