#!/usr/bin/env bash

ALLOWED_REPOS="https://github.com/uesyn/dotfiles|https://github.com/uesyn/Dockerfiles"
if [[ -n $ADDISIONAL_ALLOWED_REPOS ]]; then
  ALLOWED_REPOS="${ALLOWED_REPOS}|$ADDISIONAL_ALLOWED_REPOS"
fi
readonly DENY_BRANCH_REGEX="^(master|main|release.*)$"
readonly ALLOW_URL_REGEX='^('$ALLOWED_REPOS')$'

remote_url=$(git remote get-url origin)
branch=$(git branch --no-color --show-current)

if [[ -n $GIT_ALLOW_COMMIT ]] || [[ ! ${branch} =~ ${DENY_BRANCH_REGEX} ]] || [[ ${remote_url} =~ ${ALLOW_URL_REGEX} ]] ; then
  exit 0
fi

echo "ERROR: Failed to commit to ${branch} branch"
exit 1
