#!/usr/bin/env bash

readonly DENY_BRANCH_REGEX="^(master|main|release.*)$"
readonly ALLOW_URL_REGEX="^(https://github.com/uesyn/dotfiles)$"

remote_url=$(git remote get-url origin)
branch=$(git branch --no-color --show-current)

if [[ -n $GIT_ALLOW_COMMIT ]] || [[ ! ${branch} =~ ${DENY_BRANCH_REGEX} ]] || [[ ${remote_url} =~ ${ALLOW_URL_REGEX} ]] ; then
  exit 0
fi

echo "ERROR: Failed to commit: ${remote_ref##refs/heads/}"
echo "       If you want to commit, export GIT_ALLOW_COMMIT=yes"
exit 1
