#!/usr/bin/env bash

readonly DENY_BRANCH_REGEX="^(master|main|release.*)$"
readonly ALLOW_URL_REGEX="^(https://github.com/uesyn/dotfiles)$"

remote_url=$(git remote get-url origin)

while read local_ref local_sha2 remote_ref remote_sha1; do
  if [[ -n $GIT_ALLOW_PUSH ]] || [[ ! "${remote_ref##refs/heads/}" =~ ${DENY_BRANCH_REGEX} ]] || [[ ${remote_url} =~ ${ALLOW_URL_REGEX} ]]; then
    exit 0
  fi
  
  echo "ERROR: Failed to push to remote ${remote_ref##refs/heads/}."
  echo "       If you want to push, export GIT_ALLOW_PUSH=yes"
  exit 1
done
