let g:lsp_work_done_progress_enabled = 1
let g:lsp_document_code_action_signs_enabled = 0
let g:lsp_diagnostics_echo_cursor = 0
let g:lsp_diagnostics_echo_delay = 150
let g:lsp_diagnostics_highlights_enabled = 1
let g:lsp_diagnostics_highlights_delay = 50
let g:lsp_diagnostics_highlights_insert_mode_enabled = 0
let g:lsp_diagnostics_signs_enabled = 1
let g:lsp_diagnostics_signs_delay = 50
let g:lsp_diagnostics_signs_insert_mode_enabled = 0
let g:lsp_diagnostics_virtual_text_enabled = 0
let g:lsp_diagnostics_virtual_text_delay = 50
let g:lsp_completion_documentation_delay = 40
let g:lsp_document_highlight_delay = 50
let g:lsp_document_code_action_signs_delay = 100
let g:lsp_fold_enabled = 0
let g:lsp_text_edit_enabled = 0
let g:lsp_diagnostics_float_cursor = 1
let g:lsp_diagnostics_float_delay = 1000
let g:lsp_diagnostics_signs_error = {'text': '⛔'}

let g:lsp_settings_filetype_typescript = ['typescript-language-server', 'deno']
let g:lsp_settings_filetype_javascript = ['typescript-language-server', 'deno']
