#!/usr/bin/env zsh

flag_all=false

if [[ $1 == "-a" ]] || [[ $1 == "--all" ]]; then
  flag_all=true
fi

if [[ -x "$(command -v git)" ]]; then
  branches=$(git branch | awk '{print $1}' | grep -v '*')
  if $flag_all; then
    branches=$(git branch -a | sed -e 's/remotes\/origin\///g' | awk '{print $1}' | grep -v '*' | sort | uniq)
  fi
  local selected_dir=$(echo ${branches} | fzf)
  if [[ -n $selected_dir ]]; then
    git checkout $selected_dir
  fi
else
  echo "Please Install git!!!"
fi
