#!/usr/bin/env zsh

if [[ -x "$(command -v ghq)" ]]; then
  local selected_dir=$(ghq list | fzf)
  if [[ -n $selected_dir ]]; then
    cd $(ghq root)/${selected_dir}
  fi
else
  echo "Please Install ghq!!!"
fi
