#!/usr/bin/env zsh

git_dir(){
  local root_dir=$1
  local search_dir=$root_dir

  while true; do
    if [[ -d ${search_dir}/.git ]] || [[ -z ${search_dir} ]]; then
      break
    fi
    search_dir=${search_dir%/*}
  done
  
  if [[ -n $search_dir ]]; then
    # If in git directry
    echo -n ${search_dir}
  fi
}

open_git(){
  cd $1
  # from https://jasonmccreary.me/articles/open-github-command-line/
  github_url=`git remote -v | awk '/fetch/{print $2}' | sed -Ee 's#(git@|git://)#https://#' -e 's@com:@com/@' -e 's%\.git$%%'`;
  if [[ -x "$(command -v open)" ]]; then
    open "$github_url"
  elif [[ -x "$(command -v xdg-open)" ]]; then
    xdg-open "$github_url"
  fi
}

(open_git "$(git_dir $(pwd))")
