name: Build and push devbox
on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - 'images/devbox/**'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to ghcr.io
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./images/devbox
        file: ./images/devbox/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/uesyn/devbox:latest
