name: Devbox command Release
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ 'darwin', 'linux' ]
        goarch: [ 'arm64', 'amd64' ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'tools/devbox/go.mod'
          cache-dependency-path: 'tools/devbox/go.sum'
      - env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          cd tools/devbox
          OUTPUT=_output/devbox_${{ matrix.goos }}_${{ matrix.goarch }}
          go build  -ldflags="-w -s" -trimpath -o ${OUTPUT}
      - uses: actions/upload-artifact@v3
        with:
          name: devbox_release_${{ matrix.goos }}_${{ matrix.goarch }}
          path: |
            tools/devbox/_output/devbox_${{ matrix.goos }}_${{ matrix.goarch }}
          retention-days: 1
  publish:
    needs: [ 'build' ]
    runs-on: ubuntu-latest
    env:
      GH_REPO: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        id: download
      - run: |
          echo ${{steps.test.outputs.download-path}}
          ls ${{steps.test.outputs.download-path}}
          find ${{steps.test.outputs.download-path}}
      - run: |
          gh release delete devbox/nightly --yes || true
          git push origin :devbox/nightly || true
          gh release create -t devbox/nightly devbox/nightly devbox_release_*/*
