vim.keymap.set({"n", "v"}, "<leader>", "<Nop>")
vim.keymap.set("n", "ZZ", "<Nop>")
vim.keymap.set("n", "ZQ", "<Nop>")
vim.keymap.set("n", "q", "<Nop>")
vim.keymap.set("n", "Q", "<Nop>")
vim.keymap.set("n", "<S-l>", "<C-w>l")
vim.keymap.set("n", "<S-h>", "<C-w>h")
vim.keymap.set("n", "<S-k>", "<C-w>k")
vim.keymap.set("n", "<S-j>", "<C-w>j")
