#!/usr/bin/env bash

set -e -o pipefail

version=$1

_list_gcloud_media_urls(){
	local baseUrl
	local pageTokenOption
	local results

	baseUrl="https://www.googleapis.com/storage/v1/b/cloud-sdk-release/o"
	pageTokenOption=
	results=()

	while true; do
		mediaLinks=$(curl -fsSL ${baseUrl}${pageTokenOption} | jq -r ".items[].mediaLink")
		pageToken=$(curl -fsSL ${baseUrl}${pageTokenOption} | jq -r ".nextPageToken")

		for link in "${mediaLinks[@]}" ; do
			results=("${link}" ${results[@]})
		done

		if [[ -z ${pageToken} ]] || [[ ${pageToken} == "null" ]]; then
			break
		else
			pageTokenOption="?pageToken=${pageToken}"
		fi
	done

	for r in "${results[@]}"; do
		echo ${r}
	done
}

versions(){
	local url urls
	local i
	declare -a result

	urls=($(_list_gcloud_media_urls))

	for url in ${urls[@]}; do
		if [[ $url =~ google-cloud-sdk-([0-9]{2,3}\.[0-9]{1,3}\.[0-9]{1,3}) ]]; then
			result+=(${BASH_REMATCH[1]})
		fi
	done

	result=($(for i in ${result[@]}; do echo $i; done | sort | uniq | sort -k1nr -t'.'))
	for ((i=0; i < 20; i++));do
		echo -n "${result[${i}]} "
	done
}

if [[ -z ${version} ]]; then
  vs=($(versions))
  version=${vs[0]}
fi

unset tmpdir
tmpdir=$(mktemp --tmpdir -d gcloud.XXXXX)
function cleanup() {
  [[ -n $tmpdir ]] && rm -rf ${tmpdir}
}
trap 'cleanup' EXIT
archive_file=${tmpdir}/gcloud.tar.gz
arch=$(uname -m)
if [[ $OSTYPE =~ darwin.* ]]; then
  if [[ -z ${arch} ]]; then
    curl -o ${archive_file} https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${version}-darwin-${arch}-bundled-python.tar.gz
  else
    curl -o ${archive_file} https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${version}-darwin-${arch}.tar.gz
  fi
else
  curl -o ${archive_file} https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${version}-linux-${arch}.tar.gz
fi

cd ${tmpdir}
mkdir -p ${OPT_DIR:-${HOME}/opt}
[[ -d ${OPT_DIR}/google-cloud-sdk ]] && rm -rf ${OPT_DIR}/google-cloud-sdk
tar xzf ${archive_file} -C ${OPT_DIR}
